### ISSUE TITLE
criptominisat not building on travis

### ISSUE THREAD

**Issue by rafaeltp** [masc-ucsc/lgraph#106]
ERROR: /root/.cache/bazel/_bazel_root/2de8f8554257e007b8d6d68de18fe807/external/cryptominisat/BUILD.bazel:3:1: C++ compilation of rule '@cryptominisat//:cryptominisat' failed (Exit 1)
In file included from external/cryptominisat/src/solvertypes.h:38,
                 from external/cryptominisat/src/watched.h:31,
                 from external/cryptominisat/src/completedetachreattacher.h:27,
                 from external/cryptominisat/src/completedetachreattacher.cpp:23:
external/cryptominisat/src/solverconf.h:31:10: fatal error: cryptominisat5/solvertypesmini.h: No such file or directory
 #include "cryptominisat5/solvertypesmini.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by renau** [comment]
Solved
