### ISSUE TITLE
add support to wildcards on eprp parser

### ISSUE THREAD

**Issue by rafaeltp** [masc-ucsc/lgraph#108]
Wildcard support would be nice in the eprp commands, eg

```
inou.yosys.tolg files:./boom/*
```

Right now we need to list all files, which may be a hassle for large projects

**Comment by renau** [comment]
We have the "files" command that supports regex for matching (no bash 
wildcard)

  lgshell>help files

**Comment by rafaeltp** [comment]
It also work with quotes:

```
inou.yosys.tolg files:"./boom/*"
```
