### ISSUE TITLE
rethink meta extentions

### ISSUE THREAD

**Issue by rafaeltp** [masc-ucsc/lgraph#119]
This is related to #81 but slightly different.

We want to have a cleaner, template like way for meta tables. Currently there is considerable code replication with: clean, reload, emplace, ... and then we only have a different data type.

So ideally, we could have something like
```
struct Node_place {
  uint32_t posx;
  uint32_t posy;
};

struct Node_delay {
  double delay;
};


class LGraph_node_place {
  meta_table<Node_place> node_places;
};


class LGraph_node_delay {
  meta_table<Node_delay> node_delays;
};
```

We need to figure out how to encode the get/sets so that it is clean.
Jose suggested something like (not clear how to implement but general idea):

```
graph.get_node(idx).node_place.get().x() //or
graph.get_port(idx, pid).node_delay.set(0.17)
```

**Comment by renau** [comment]
The new attribute/meta API being worked solves this issue
