### ISSUE TITLE
Thread pool cannot terminate

### ISSUE THREAD

**Issue by clin99** [masc-ucsc/lgraph#123]
**Describe the bug**
Sometimes the thread pool will get stuck in destructor.

**To Reproduce**
To reproduce this problem, you can increase the number of threads (I set the thread_count to 4 in my test and I use spmc) and insert many jobs and run the program multiple times.

**To solve**
Change this line https://github.com/masc-ucsc/lgraph/blob/f057821e555c9d5b347e003d87aac275225447db/core/thread_pool.hpp#L116
to 
`{
   std::lock_guard<std::mutex> lock(queue_mutex);
   finishing = true;
}` 

**Additional context**
Another issue is the assertion 
https://github.com/masc-ucsc/lgraph/blob/f057821e555c9d5b347e003d87aac275225447db/core/thread_pool.hpp#L147

This assertion might fail even all jobs are executed. I think this assertion is not needed.

**Comment by renau** [comment]
Thanks, I have patched in my local edits. Next push will include them.
