### ISSUE TITLE
Class 'RConstPodIterator' has a constructor with 1 argument that is not explicit.

### ISSUE THREAD

**Issue by renau** [masc-ucsc/lgraph#19]
#### Occurred on:
+ **Commit**:  fef07e3cbb675e0789d71b0122335035fd7c1587
+ **File**:    [core/tests/iterator_tst.cpp](https://github.com/masc-ucsc/lgraph/blob/fef07e3cbb675e0789d71b0122335035fd7c1587/core/tests/iterator_tst.cpp)
+ **LineNum**: [33](https://github.com/masc-ucsc/lgraph/blob/fef07e3cbb675e0789d71b0122335035fd7c1587/core/tests/iterator_tst.cpp#L33)
+ **Code**:    `RConstPodIterator(const DataType *ptr): ptr(ptr){}`

    
#### Currently on:
+ **Commit**:  39380e1a50790fbac8ce2432931c50037df22890
+ **File**:    [core/tests/iterator_tst.cpp](https://github.com/masc-ucsc/lgraph/blob/39380e1a50790fbac8ce2432931c50037df22890/core/tests/iterator_tst.cpp)
+ **LineNum**: [33](https://github.com/masc-ucsc/lgraph/blob/39380e1a50790fbac8ce2432931c50037df22890/core/tests/iterator_tst.cpp#L33)

**Comment by birdeclipse** [comment]
close it for now as iterator_tst.cpp is no longer in the repo
