### ISSUE TITLE
struct member 'index_bits::bits' is never used.

### ISSUE THREAD

**Issue by renau** [masc-ucsc/lgraph#21]
#### Occurred on:
+ **Commit**:  fef07e3cbb675e0789d71b0122335035fd7c1587
+ **File**:    [inou/blif/inou_blif.hpp](https://github.com/masc-ucsc/lgraph/blob/fef07e3cbb675e0789d71b0122335035fd7c1587/inou/blif/inou_blif.hpp)
+ **LineNum**: [34](https://github.com/masc-ucsc/lgraph/blob/fef07e3cbb675e0789d71b0122335035fd7c1587/inou/blif/inou_blif.hpp#L34)
+ **Code**:    `int bits[2];`

    
#### Currently on:
+ **Commit**:  39380e1a50790fbac8ce2432931c50037df22890
+ **File**:    [inou/blif/inou_blif.hpp](https://github.com/masc-ucsc/lgraph/blob/39380e1a50790fbac8ce2432931c50037df22890/inou/blif/inou_blif.hpp)
+ **LineNum**: [34](https://github.com/masc-ucsc/lgraph/blob/39380e1a50790fbac8ce2432931c50037df22890/inou/blif/inou_blif.hpp#L34)

**Comment by birdeclipse** [comment]
remove inou_blif and try to merge it into inou_abc
