### ISSUE TITLE
fprintf format string requires 3 parameters but only 2 are given.

### ISSUE THREAD

**Issue by renau** [masc-ucsc/lgraph#22]
#### Occurred on:
+ **Commit**:  fef07e3cbb675e0789d71b0122335035fd7c1587
+ **File**:    [misc/def/defrw/defrw.cpp](https://github.com/masc-ucsc/lgraph/blob/fef07e3cbb675e0789d71b0122335035fd7c1587/misc/def/defrw/defrw.cpp)
+ **LineNum**: [2552](https://github.com/masc-ucsc/lgraph/blob/fef07e3cbb675e0789d71b0122335035fd7c1587/misc/def/defrw/defrw.cpp#L2552)
+ **Code**:    `fprintf(fout, "- MACRO %s THRUPIN %s %s ",`

    
#### Currently on:
+ **Commit**:  39380e1a50790fbac8ce2432931c50037df22890
+ **File**:    [misc/def/defrw/defrw.cpp](https://github.com/masc-ucsc/lgraph/blob/39380e1a50790fbac8ce2432931c50037df22890/misc/def/defrw/defrw.cpp)
+ **LineNum**: [2552](https://github.com/masc-ucsc/lgraph/blob/39380e1a50790fbac8ce2432931c50037df22890/misc/def/defrw/defrw.cpp#L2552)

**Comment by birdeclipse** [comment]
Fixed, this is a third party code bug, but easy to fix
