### ISSUE TITLE
struct member 'tech_layer_s_::horizontal' is never used.

### ISSUE THREAD

**Issue by renau** [masc-ucsc/lgraph#33]
#### Occurred on:
+ **Commit**:  fef07e3cbb675e0789d71b0122335035fd7c1587
+ **File**:    [core/tech_library.hpp](https://github.com/masc-ucsc/lgraph/blob/fef07e3cbb675e0789d71b0122335035fd7c1587/core/tech_library.hpp)
+ **LineNum**: [217](https://github.com/masc-ucsc/lgraph/blob/fef07e3cbb675e0789d71b0122335035fd7c1587/core/tech_library.hpp#L217)
+ **Code**:    `bool                horizontal;`

    
#### Currently on:
+ **Commit**:  9c6a6d814f2301bd2ead4cb7c1c79beb908a3015
+ **File**:    [core/tech_library.hpp](https://github.com/masc-ucsc/lgraph/blob/9c6a6d814f2301bd2ead4cb7c1c79beb908a3015/core/tech_library.hpp)
+ **LineNum**: [225](https://github.com/masc-ucsc/lgraph/blob/9c6a6d814f2301bd2ead4cb7c1c79beb908a3015/core/tech_library.hpp#L225)

**Comment by birdeclipse** [comment]
it is used in inou_lef.cpp / lglefdef.hpp
