### ISSUE TITLE
Undefined behaviour, pointer arithmetic 'val-1' is out of bounds.

### ISSUE THREAD

**Issue by renau** [masc-ucsc/lgraph#36]
#### Occurred on:
+ **Commit**:  fef07e3cbb675e0789d71b0122335035fd7c1587
+ **File**:    [core/tests/iterator_tst.cpp](https://github.com/masc-ucsc/lgraph/blob/fef07e3cbb675e0789d71b0122335035fd7c1587/core/tests/iterator_tst.cpp)
+ **LineNum**: [59](https://github.com/masc-ucsc/lgraph/blob/fef07e3cbb675e0789d71b0122335035fd7c1587/core/tests/iterator_tst.cpp#L59)
+ **Code**:    `RConstPodIterator rend() const { return RConstPodIterator(val-1); }`

    
#### Currently on:
+ **Commit**:  9c6a6d814f2301bd2ead4cb7c1c79beb908a3015
+ **File**:    [core/tests/iterator_tst.cpp](https://github.com/masc-ucsc/lgraph/blob/9c6a6d814f2301bd2ead4cb7c1c79beb908a3015/core/tests/iterator_tst.cpp)
+ **LineNum**: [59](https://github.com/masc-ucsc/lgraph/blob/9c6a6d814f2301bd2ead4cb7c1c79beb908a3015/core/tests/iterator_tst.cpp#L59)

**Comment by birdeclipse** [comment]
iterator_tst.cpp is deleted for now.
