### ISSUE TITLE
Return value of function log() is not used.

### ISSUE THREAD

**Issue by renau** [masc-ucsc/lgraph#44]
#### Occurred on:
+ **Commit**:  fef07e3cbb675e0789d71b0122335035fd7c1587
+ **File**:    [inou/yosys/out_yosys.cpp](https://github.com/masc-ucsc/lgraph/blob/fef07e3cbb675e0789d71b0122335035fd7c1587/inou/yosys/out_yosys.cpp)
+ **LineNum**: [28](https://github.com/masc-ucsc/lgraph/blob/fef07e3cbb675e0789d71b0122335035fd7c1587/inou/yosys/out_yosys.cpp#L28)
+ **Code**:    `log("\n");`

    
#### Currently on:
+ **Commit**:  9c6a6d814f2301bd2ead4cb7c1c79beb908a3015
+ **File**:    [inou/yosys/out_yosys.cpp](https://github.com/masc-ucsc/lgraph/blob/9c6a6d814f2301bd2ead4cb7c1c79beb908a3015/inou/yosys/out_yosys.cpp)
+ **LineNum**: [28](https://github.com/masc-ucsc/lgraph/blob/9c6a6d814f2301bd2ead4cb7c1c79beb908a3015/inou/yosys/out_yosys.cpp#L28)

**Comment by birdeclipse** [comment]
This is not a real issue. close it
