### ISSUE TITLE
Fix 'Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.' issue in test\abc.sh

### ISSUE THREAD

**Issue by renau** [masc-ucsc/lgraph#49]
[CodeFactor](https://www.codefactor.io/repository/github/masc-ucsc/lgraph/overview/master) found an issue: Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.

It's currently on:
[test\abc.sh:26
](https://www.codefactor.io/repository/github/masc-ucsc/lgraph/source/master/test/abc.sh#L26)

**Comment by birdeclipse** [comment]
fixed
