### ISSUE TITLE
Statements following return, break, continue, goto or throw will never be executed.

### ISSUE THREAD

**Issue by renau** [masc-ucsc/lgraph#5]
#### Occurred on:
+ **Commit**:  fef07e3cbb675e0789d71b0122335035fd7c1587
+ **File**:    [core/lgedge.cpp](https://github.com/masc-ucsc/lgraph/blob/fef07e3cbb675e0789d71b0122335035fd7c1587/core/lgedge.cpp)
+ **LineNum**: [85](https://github.com/masc-ucsc/lgraph/blob/fef07e3cbb675e0789d71b0122335035fd7c1587/core/lgedge.cpp#L85)
+ **Code**:    `assert(false); // Not found all over`

    
#### Currently on:
+ **Commit**:  1be742665a72793fb15ac1c1c7deb598735c8001
+ **File**:    [core/lgedge.cpp](https://github.com/masc-ucsc/lgraph/blob/1be742665a72793fb15ac1c1c7deb598735c8001/core/lgedge.cpp)
+ **LineNum**: [83](https://github.com/masc-ucsc/lgraph/blob/1be742665a72793fb15ac1c1c7deb598735c8001/core/lgedge.cpp#L83)

**Comment by birdeclipse** [comment]
the code has changed. close this issue
