### ISSUE TITLE
cops/live code replication

### ISSUE THREAD

**Issue by renau** [masc-ucsc/lgraph#52]
Found 6 duplicate lines with fingerprint da8f38b527666b151534c2f634bf42b2 in the following files:
 Between lines 28 and 34 in /mada/users/renau/projs/lgraph/cops/live/live_options.cpp
 Between lines 27 and 33 in /mada/users/renau/projs/lgraph/cops/live/invariant_options.cpp
Found 6 duplicate lines with fingerprint 0f4d2ce83213fbb0eb4741253a73d8b0 in the following files:
 Between lines 168 and 174 in /mada/users/renau/projs/lgraph/cops/live/live_common.hpp
 Between lines 33 and 39 in /mada/users/renau/projs/lgraph/cops/live/live_common.hpp
Found 7 duplicate lines with fingerprint e3649037e1fbe9de9a679a03e6099be6 in the following files:
 Between lines 79 and 88 in /mada/users/renau/projs/lgraph/cops/live/live_common.hpp
 Between lines 107 and 116 in /mada/users/renau/projs/lgraph/cops/live/live_common.hpp
Found 7 duplicate lines with fingerprint 9d1ee19bc2615287cf4077e95f977a54 in the following files:
 Between lines 113 and 121 in /mada/users/renau/projs/lgraph/cops/live/live_common.hpp
 Between lines 242 and 250 in /mada/users/renau/projs/lgraph/cops/live/live_common.hpp
Found 8 duplicate lines with fingerprint 90203b87fa71866c8ae9a4d47892dead in the following files:
 Between lines 645 and 652 in /mada/users/renau/projs/lgraph/cops/live/diff_finder.cpp
 Between lines 632 and 639 in /mada/users/renau/projs/lgraph/cops/live/diff_finder.cpp
Found 10 duplicate lines with fingerprint 0996b3a248df073518e56d057dd0c227 in the following files:
 Between lines 143 and 154 in /mada/users/renau/projs/lgraph/cops/live/live_common.hpp
 Between lines 14 and 25 in /mada/users/renau/projs/lgraph/cops/live/live_common.hpp
Found 11 duplicate lines with fingerprint 0115650967c9a8f007675b56dc11565e in the following files:
 Between lines 63 and 77 in /mada/users/renau/projs/lgraph/cops/live/live_common.hpp
 Between lines 90 and 104 in /mada/users/renau/projs/lgraph/cops/live/live_common.hpp

**Comment by rafaeltp** [comment]
How did you generate those?
I will close all the issues that point to code replication since they are most likely out dated.
It would be nice to re-check though
