### ISSUE TITLE
Verbosity level

### ISSUE THREAD

**Issue by rafaeltp** [masc-ucsc/lgraph#61]
It would be nice to be able to change verbosity level at runtime.
We have some warnings that are currently printed by deafult and some messages that are added/removed by ifdefs.

This could be a flag in the Option pack or on the Python caller.
Something like `-v` `-vv` `-vvvvvv` or `--verbosity=X` for different levels.

This is also related to the combined error reporting classes, although it is not the same.

**Comment by renau** [comment]
I did this with LGRAPH_LOG variable. Levels are info,warn,err,debug. Same as spdlog support
