### ISSUE TITLE
New And_Op and Or_Op

### ISSUE THREAD

**Issue by renau** [masc-ucsc/lgraph#93]
We need order for the inputs to regenerate the fluid.

Ops will have multiple input pids 0,1,2,3,4. the pid implies order

**Comment by renau** [comment]
Any update on this?

To avoiding patching yosys, we may want to support both.

**Comment by swang203** [comment]
Hi, I have not been able to update this.
But how to support priority AND and OR without patching the existing one in lgyosys_dump/
lgyosys_tolg? Create an And/Or_Fluid_Op and in Pyrope compiler we always use it?

**Comment by rafaeltp** [comment]
I don't think there is anything needed here to support the operators described. You should be able to connect to any PIDs for And_Op and Or_Op. Re-open if there is an issue when you create an example.
